### ISSUE TITLE
undefined: spdy.NewClientTransport

### ISSUE THREAD

**Issue by joao-parana** [docker/libchan#103]
I was using v0.1.0 version and my program ran OK. 

    transport, err := spdy.NewClientTransport(client)

Now, using origin master, I get this error: 

    undefined: spdy.NewClientTransport

Which method I need to use instead ?

**Comment by dmcgowan** [comment]
The spdy transport is being abstracted out. A stream provider is created then used to create a transport.

```
provider, err := spdy.NewSpdyStreamProvider(client, false)
...
transport := spdy.NewTransport(provider)
```

The spdy directory will soon be renamed since the implementation has been generalized and rather spdy is choosen by creating the creating the provider (the sream multiplex implementation). Notice creating a transport will no longer return an error.

Feedback on this interface is appreciated. Eventually http2 support will be added and only the provider initialization should need to change.
